# General configurations applicable to all builds
[term]
quiet = false          # whether cargo output is quiet
verbose = true         # whether cargo provides verbose output
color = 'auto'         # whether cargo colorizes output
hyperlinks = true      # whether cargo inserts links into output
progress.when = 'auto' # whether cargo shows progress bar
progress.width = 80    # width of progress bar

#[target.'cfg(all(target_arch = "arm", target_os = "none"))']